name: release

on:
  push:
    branches:
    - release

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GP_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: release
        DEFAULT_BUMP: 'patch'
        REPO_OWNER: 'tool3'
